### PR TITLE
Deprecate `dask-xgboost`

### LINKED ISSUE #80: Archive this repo?
Since the functionality has been moved to xgboost itself. Would now be the appropriate time to archive this repo?

### PR DESCRIPTION
**Pull request by jrbourbeau**
Closes https://github.com/dask/dask-xgboost/issues/80

cc @TomAugspurger @trivialfis @JohnZed @jakirkham

### CODE REVIEW

**Review by TomAugspurger — COMMENTED** [review]
Thanks! Do you plan to make a release with this change? If so, you might want to bump the version number.

I'm also totally fine with leaving the released version as the last release, and just archiving things on GitHub.

**Comment by jrbourbeau** [comment]
Yeah, I'm happy to push a final `0.2.0` release out with this change. Could you add me to PyPI?

I'm also inclined to not worry about the seg fault causing CI to fail and just push things out as is

**Comment by TomAugspurger** [comment]
Thanks, added to PyPI

**Comment by trivialfis** [comment]
Thanks for working on this!  I will check the segfault after resgistering another github account for logging into circleci...

**Comment by trivialfis** [comment]
The segfault is caused by old xgboost (0.90) predict function not being thread safe.  I ran the tests with latest xgboost and didn't reproduce.  It can be safely ignored.

**Comment by TomAugspurger** [comment]
Thanks all.

**Comment by jrbourbeau** [comment]
Thanks @TomAugspurger. Pushing out a release now...

**Pull request merged**
