### PR TITLE
Followup on multiclass

### PR DESCRIPTION
**Pull request by TomAugspurger**
We more closely match the upstream behavior now.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Here's a seemingly minimal failure

```
# test_it.py
import pytest
from distributed.utils_test import loop, cluster  # noqa
from distributed import Client


@pytest.mark.timeout(5)
def test_multiclass_classifier(loop):  # noqa
    with cluster() as (s, [_, _]):
        with Client(s['address'], loop=loop):
            assert 1
```

Run with `pytest test_it.py -rsx -v -n 1 --boxed test_it.py `

On distributed master, that fails with `--boxed`, passes without. Bisecting now.

**Comment by TomAugspurger** [comment]
git bisect pionts to https://github.com/dask/distributed/commit/cb10d6b10ad7800648b44ab3b194220d1e6fc5f8

It's not immediately clear to me why that would be.

**Comment by TomAugspurger** [comment]
But changing https://github.com/dask/distributed/commit/cb10d6b10ad7800648b44ab3b194220d1e6fc5f8#diff-5e17f71205ff4d743e567250466d4725R22 from `max_workers=1` to `2` "fixes" things.

**Comment by mrocklin** [comment]
That's interesting.  Quick googling says that this runs every test in a forked subprocess.  This this correct?

**Comment by mrocklin** [comment]
This -> `--boxed`

**Comment by TomAugspurger** [comment]
Not sure about fork vs. spawn, but that's the basic idea. We needed it
initially because we had an issue with calling some rabit init function in
subsequent tests. I'll find the details later tonight.

**Comment by mrocklin** [comment]
My first guess is that we're forking while there is a thread active in the
ThreadPoolExecutor and so the forked process has a TPE that's wonky.  Just
a guess though.

**Comment by TomAugspurger** [comment]
I'm pretty stumped by this. I made a PR https://github.com/dmlc/xgboost/pull/3656, but it's not clear that solves our problem.

So I'm going to try to work around it. It *seems* like rabit.init / finalize should only be called once per thread. We currently call init / finalize each each partition during training and prediction.

My plan was to store whether rabit.init has been called on a thread local and register some kind of callback to run finalize when the worker is closed... But this all seems fragile.

**Comment by TomAugspurger** [comment]
Very hacky code right now, just experimenting. This seems incorrect though

```
distributed.worker - INFO - Starting Rabit, Rank 1
distributed.worker - WARNING - rabit.init already called on thread 123145586491392
distributed.worker - INFO - Starting Rabit, Rank 0
distributed.worker - INFO - Starting Rabit, Rank 0
distributed.worker - INFO - Starting Rabit, Rank 0
distributed.worker - INFO - Starting Rabit, Rank 0
distributed.worker - INFO - Starting Rabit, Rank 0
distributed.worker - INFO - Starting Rabit, Rank 0
distributed.worker - INFO - Starting Rabit, Rank 0
```

I think my entire approach is wrong.

**Comment by mrocklin** [comment]
I'm happy to take a look.  Is the right way to investigate this to try to
run a particular dask-ml test with the recent release of distributed ?

**Comment by TomAugspurger** [comment]
By "this" I assume you mean the change in distributed? If so, then

```
pytest test_it.py -rsx -v -n 1 --boxed test_it.py
```

on this file

```python
# file: test_it.py
import pytest
from distributed.utils_test import loop, cluster  # noqa
from distributed import Client


@pytest.mark.timeout(5)
def test_multiclass_classifier(loop):  # noqa
    with cluster() as (s, [_, _]):
        with Client(s['address'], loop=loop):
            assert 1

```

**Comment by mrocklin** [comment]
I'm also happy to help with things on the XGBoost side.  I can also look into making the dask/distributed library forksafe, but it's not entirely trivial.

Interestingly, the following works for me :+1: 

```python
In [1]: import xgboost

In [2]: xgboost.rabit.init()

In [3]: xgboost.rabit.finalize()

In [4]: xgboost.rabit.init()

In [5]: xgboost.rabit.finalize()
```

**Comment by mrocklin** [comment]
I've tried this on both 0.72 and 0.80

**Comment by TomAugspurger** [comment]
Hmm I built xgboost from source. Perhaps that's why.

FWIW, I havn't noticed this outside the test suite, and am able to work around it by monkeypatching `distributed.comm.utils._offload_executor = ThreadPoolExecutor(max_workers=2)` within `test_core.py`. That's not ideal, but at this point I'm comfortable with that :)

**Comment by mrocklin** [comment]
Yeah, and it's possible that we can make that change.

That will allow Python to deserialize two objects at the same time, which
isn't necessarily a bad thing.

**Pull request merged**
